name: Continuous integration
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      # Build the Java project using Maven 
      - name: Build with Maven
        run: mvn clean install


      # Step 5: Archive build artifacts (optional)
      - name: Archive build artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/*.jar

  deploy:
    needs: build  # Run deploy job only if build job succeeds
    runs-on: ubuntu-latest

    steps:
      # Step 6: Trigger Jenkins deployment job after successful build
      - name: Trigger Jenkins deployment
        run: |
          curl -X POST "http://8ce0-69-157-125-23.ngrok-free.app/job/java-tomcat/buildWithParameters?token=${{secrets.JENKINS_API_TOKEN}}&BUILD_ID=${{ github.run_id }}&GIT_COMMIT=${{ github.sha }}"

        env:
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
